# The only possible value is "2".
version: "2"

# Options for analysis running.
run:
  timeout: 10m # 
  # Which dirs to skip: issues from them won't be reported.
  # Can use regexp here: `generated.*`, regexp is applied on full path.
  # Default value is empty list,
  # but default dirs are skipped independently of this option's value (see skip-dirs-use-default).
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  modules-download-mode: mod # 
  go: '1.24'

linters:
  enable: # 
    - asciicheck
    - bodyclose
    - dogsled
    - copyloopvar
    - goconst
    - gosec
    - unconvert
    - misspell
    - reassign
    - mirror
    - durationcheck
    - whitespace
    - usetesting
    - bidichk
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
    rules:
      - path: _test\.go
        linters:
          - gosec
    paths:
      - pkg/generated
      - pkg/internal
      - pkg/model
  settings:
    staticcheck:
      checks: 
        - all
        - -S1039 
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
    dogsled:
      max-blank-identifiers: 3
    misspell:
      locale: US
    

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      # Section configuration to compare against.
      # Section names are case-insensitive and may contain parameters in ().
      # Default: ["standard", "default"]
      sections:
        - standard # Captures all standard packages if they do not match another section.
        - default # Contains all imports that could not be matched to another section type.
        - prefix(github.com/ggsrc) # our internal packages
        - prefix(github.com/NFTGalaxy) # our internal packages
        - prefix(github.com/NFTGalaxy/galaxy-graphigo) # local
      # Separators that should be present between sections.
      # Default: ["newLine"]
      custom-order: true